## DESCRIPTION

[Project\_Note\_BibliometrixReportSystem](Bibliometrix%20Report%20System)

%%This is a Bibliometric analysis focused on `Educational technology`.

This analysis covers the timespan `1957:2023`, drawing from `901` sources including journals, books, and other documents, totaling `4390` documents. During this period, the field experienced an annual growth rate of `9.64`, with the average age of documents being `12.3` years. On average, each document received `21.32` citations, amounting to `2.4` citations per year, contributing to a total of `148383` references.

The document types in this analysis include `3600` articles, `118` articles in early access, `78` articles that are proceedings papers, `112` editorial materials, {{proceedings paper}} proceedings papers, `291` reviews, {{review; book chapter}} book chapter reviews, and `19` early access reviews.

In the realm of document contents, there are `3596` instances of Keywords Plus and `8336` Author’s Keywords. The number of authors involved is `10012`, with a total of `12216` author appearances. Among these, `1105` authors have produced single-authored documents.

Focusing on author collaboration, there are `1263` single-authored documents. On average, there are `0.438` documents per author and `2.78` co-authors per document. The rate of international co-authorships in this field is `16.47`.%%

## Annual ⏱️

### Annual Scientific Production

![AnnualProdution](file:///Users/yamlam/Documents/obsdiannote/🧪%20Script%20Labs/Thematic//Educational%20technology/exports/S0-BasicStatistics-AnnualProdution-Educational%20technology.png)

Combined from `Annual Scientific Production`, `Averge Articles Citations per Year`, `Averge Total Citations per Year`

-   Relavant source: [AnnualProdution.csv](file:/Users/yamlam/Documents/obsdiannote/🧪%20Script%20Labs/Thematic//Educational%20technology/exports/S0-BasicStatistics-AnnualProdution-Educational%20technology.csv)
-   Local note: [Average Article Citations per Year](Average%20Article%20Citations%20per%20Year)

### correlations

Strong Positive Correlation:
- `Articles` and `Year` with value: 0.739940955293611
- `MeanTCperYear` and `Year` with value: 0.868270515892594
- `MeanTCperYear` and `Articles` with value: 0.793372935695893
- `MeanTCperYear` and `MeanTCperArt` with value: 0.701641016584508

%% Think about TRUE/FALSE
- When `Articles/N` increases, `MeanTCperYear`(the average number of citations per year) increases.
- When `Articles/N` (the number of publications) increases, `MeanTCperArt`(the average number of citations per article) decreases. This may be due to researchers publishing more articles in the same field, resulting in fewer citations per article.
%%

|      | Year | Articles | MeanTCperArt | MeanTCperYear |
|:-----|-----:|---------:|-------------:|--------------:|
| 1957 | 1957 |        1 |    0.0000000 |     0.0000000 |
| 1958 | 1958 |        0 |    0.0000000 |     0.0000000 |
| 1959 | 1959 |        1 |   12.0000000 |     0.1846154 |
| 1960 | 1960 |        1 |    1.0000000 |     0.0156250 |
| 1961 | 1961 |        1 |    0.0000000 |     0.0000000 |
| 1962 | 1962 |        2 |    0.0000000 |     0.0000000 |
| 1963 | 1963 |        2 |    0.5000000 |     0.0081967 |
| 1964 | 1964 |        1 |    1.0000000 |     0.0166667 |
| 1965 | 1965 |        2 |    0.0000000 |     0.0000000 |
| 1966 | 1966 |       11 |    0.0909091 |     0.0015674 |
| 1967 | 1967 |       14 |    0.2142857 |     0.0037594 |
| 1968 | 1968 |       25 |    0.9600000 |     0.0171429 |
| 1969 | 1969 |       35 |    0.3428571 |     0.0062338 |
| 1970 | 1970 |       22 |    0.0909091 |     0.0016835 |
| 1971 | 1971 |       17 |    0.3529412 |     0.0066593 |
| 1972 | 1972 |       25 |    0.4800000 |     0.0092308 |
| 1973 | 1973 |       14 |    0.6428571 |     0.0126050 |
| 1974 | 1974 |       19 |    0.4210526 |     0.0084211 |
| 1975 | 1975 |       16 |    0.4375000 |     0.0089286 |
| 1976 | 1976 |       25 |    1.0400000 |     0.0216667 |
| 1977 | 1977 |       17 |    1.2352941 |     0.0262829 |
| 1978 | 1978 |       23 |    1.3478261 |     0.0293006 |
| 1979 | 1979 |       23 |    1.1304348 |     0.0251208 |
| 1980 | 1980 |       23 |    0.8260870 |     0.0187747 |
| 1981 | 1981 |        8 |    0.7500000 |     0.0174419 |
| 1982 | 1982 |       13 |    0.6923077 |     0.0164835 |
| 1983 | 1983 |        8 |    1.6250000 |     0.0396341 |
| 1984 | 1984 |        7 |    3.4285714 |     0.0857143 |
| 1985 | 1985 |       19 |    1.6842105 |     0.0431849 |
| 1986 | 1986 |       16 |    1.5000000 |     0.0394737 |
| 1987 | 1987 |       11 |    4.1818182 |     0.1130221 |
| 1988 | 1988 |        4 |    1.0000000 |     0.0277778 |
| 1989 | 1989 |       14 |    7.3571429 |     0.2102041 |
| 1990 | 1990 |       12 |    1.0000000 |     0.0294118 |
| 1991 | 1991 |       14 |    5.2142857 |     0.1580087 |
| 1992 | 1992 |       15 |   10.8000000 |     0.3375000 |
| 1993 | 1993 |       11 |    7.5454545 |     0.2434018 |
| 1994 | 1994 |       22 |   85.6363636 |     2.8545455 |
| 1995 | 1995 |       11 |   55.4545455 |     1.9122257 |
| 1996 | 1996 |        9 |    7.1111111 |     0.2539683 |
| 1997 | 1997 |       19 |   30.4736842 |     1.1286550 |
| 1998 | 1998 |       28 |   24.1071429 |     0.9271978 |
| 1999 | 1999 |       27 |   11.7407407 |     0.4696296 |
| 2000 | 2000 |       25 |   51.2800000 |     2.1366667 |
| 2001 | 2001 |       26 |   37.8846154 |     1.6471572 |
| 2002 | 2002 |       26 |   29.4230769 |     1.3374126 |
| 2003 | 2003 |       42 |   62.8095238 |     2.9909297 |
| 2004 | 2004 |       52 |   27.0000000 |     1.3500000 |
| 2005 | 2005 |       51 |   42.1176471 |     2.2167183 |
| 2006 | 2006 |       44 |   28.7500000 |     1.5972222 |
| 2007 | 2007 |       55 |   49.8181818 |     2.9304813 |
| 2008 | 2008 |      104 |   41.1538462 |     2.5721154 |
| 2009 | 2009 |       96 |   48.3020833 |     3.2201389 |
| 2010 | 2010 |      137 |   43.9416058 |     3.1386861 |
| 2011 | 2011 |      116 |   29.5775862 |     2.2751989 |
| 2012 | 2012 |      142 |   40.5070423 |     3.3755869 |
| 2013 | 2013 |      166 |   34.3253012 |     3.1204819 |
| 2014 | 2014 |      157 |   32.6050955 |     3.2605096 |
| 2015 | 2015 |      170 |   24.9058824 |     2.7673203 |
| 2016 | 2016 |      179 |   27.7039106 |     3.4629888 |
| 2017 | 2017 |      204 |   28.9705882 |     4.1386555 |
| 2018 | 2018 |      247 |   22.7004049 |     3.7834008 |
| 2019 | 2019 |      280 |   22.3285714 |     4.4657143 |
| 2020 | 2020 |      307 |   18.6058632 |     4.6514658 |
| 2021 | 2021 |      357 |   11.8963585 |     3.9654528 |
| 2022 | 2022 |      384 |    5.9635417 |     2.9817708 |
| 2023 | 2023 |      435 |    2.9471264 |     2.9471264 |

(*Table above: Annual Scientific Production*)

## Countries 🌏

### Most Productive Countries

![Plot Countries](file:/Users/yamlam/Documents/obsdiannote/🧪%20Script%20Labs/Thematic/Educational%20technology/Report_Educational%20technology_files/figure-markdown_strict/Summary_biblioAnalysis-2.png)

| Country        | Articles | Freq     | SCP | MCP | MCP\_Ratio |
|:---------------|:---------|:---------|:----|:----|:-----------|
| USA            | 1046     | 0.258847 | 939 | 107 | 0.1023     |
| CHINA          | 473      | 0.117050 | 380 | 93  | 0.1966     |
| UNITED KINGDOM | 332      | 0.082158 | 286 | 46  | 0.1386     |
| SPAIN          | 258      | 0.063846 | 213 | 45  | 0.1744     |
| AUSTRALIA      | 201      | 0.049740 | 160 | 41  | 0.2040     |

(*Table above: Corresponding Author’s Countries*)

-   Relavant note: [MCP](MCP%20-%20Multiple%20Country%20Publications). 理解一个国家的研究环境有多开放和协作

### correlations

- [x] Prompt 通过 `Corresponding Author's Countries` 与 `Total Citations per Country` 的对比找到冲突等特征. ✅ 2024-03-31

|     | TC\_rank | Country        |    TC | AvgArtCit | Articles | SCP | MCP | MCP\_Ratio |
|:----|---------:|:---------------|------:|----------:|---------:|----:|----:|-----------:|
| 10  |       10 | NETHERLANDS    |  2057 |     32.65 |       63 |  53 |  10 |     0.1587 |
| 11  |        1 | USA            | 32267 |     30.85 |     1046 | 939 | 107 |     0.1023 |
| 14  |       14 | GREECE         |  1453 |     29.06 |       50 |  44 |   6 |     0.1200 |
| 15  |       11 | KOREA          |  1878 |     28.45 |       66 |  50 |  16 |     0.2424 |
| 16  |        9 | GERMANY        |  2190 |     28.44 |       77 |  54 |  23 |     0.2987 |
| 17  |       16 | MALAYSIA       |  1202 |     26.71 |       45 |  30 |  15 |     0.3333 |
| 20  |        4 | AUSTRALIA      |  4916 |     24.46 |      201 | 160 |  41 |     0.2040 |
| 21  |        3 | UNITED KINGDOM |  7979 |     24.03 |      332 | 286 |  46 |     0.1386 |
| 24  |        6 | TURKEY         |  3678 |     19.67 |      187 | 170 |  17 |     0.0909 |
| 27  |        5 | SPAIN          |  4859 |     18.83 |      258 | 213 |  45 |     0.1744 |
| 28  |        2 | CHINA          |  8903 |     18.82 |      473 | 380 |  93 |     0.1966 |
| 36  |       18 | FINLAND        |   749 |     16.64 |       45 |  40 |   5 |     0.1111 |
| 37  |       17 | SWEDEN         |  1137 |     16.24 |       70 |  60 |  10 |     0.1429 |
| 38  |       12 | CANADA         |  1741 |     15.41 |      113 |  96 |  17 |     0.1504 |
| 39  |       19 | ITALY          |   692 |     14.72 |       47 |  34 |  13 |     0.2766 |
| 57  |       21 | SOUTH AFRICA   |   473 |      9.85 |       48 |  42 |   6 |     0.1250 |
| 64  |       15 | BRAZIL         |  1259 |      8.93 |      141 | 125 |  16 |     0.1135 |

(*Table above: Corresponding Author’s Countries*)

table is filtered by mean of ‘Articles’ &gt; 42.09375

Strong Positive Correlation:
- `Articles` and `TC` with value: 0.97785935174112
- `SCP` and `TC` with value: 0.982474613357216
- `MCP` and `TC` with value: 0.882759987785499
- `SCP` and `Articles` with value: 0.998823926204595
- `MCP` and `Articles` with value: 0.943160360851524
- `MCP` and `SCP` with value: 0.925937833153151

%%
Highlight:
If the more articles published(`Articles/N`),
- the less citations(`Total.Citations`) received?
- the less citations per article(`Average.Article.Citations`) received?
if so, it may be due to researchers publishing more articles in the same field, but they are `not necessarily high-quality articles`.
%%

## Authors 🧑‍🏫

| Country        | Total Citations | Average Article Citations |
|:---------------|:----------------|:--------------------------|
| USA            | 32267           | 30.85                     |
| CHINA          | 8903            | 18.82                     |
| UNITED KINGDOM | 7979            | 24.03                     |
| AUSTRALIA      | 4916            | 24.46                     |
| SPAIN          | 4859            | 18.83                     |

(*Table above: Total Citations per Country*)

[Average\_Article\_Citations\_per\_Country](Average%20Article%20Citations%20per%20Country) 较高的平均文章引用表明更大的研究影响力。总引用量只显示数量。(有时可能只是他们发表数量多 )

### Most Productive Authors

![MostProdAuthors](file:/Users/yamlam/Documents/obsdiannote/🧪%20Script%20Labs/Thematic/Educational%20technology/Report_Educational%20technology_files/figure-markdown_strict/Summary_biblioAnalysis-1.png)

| Authors   | Articles | Authors    | Articles Fractionalized |
|:----------|:---------|:-----------|:------------------------|
| TEO T     | 28       | TEO T      | 14.95                   |
| HWANG GJ  | 25       | SELWYN N   | 11.17                   |
| SELWYN N  | 20       | HWANG GJ   | 7.52                    |
| TONDEUR J | 17       | MERTALA P  | 5.83                    |
| TSAI CC   | 16       | SPECTOR JM | 5.54                    |

(*Table above: Most Productive Authors*)

Source summary:[csv](file:/Users/yamlam/Documents/obsdiannote/🧪%20Script%20Labs/Thematic//Educational%20technology/exports/S0-BasicStatistics-MostProdAuthors-Educational%20technology.csv).
Relavant note: [MostProdAuthors](MostProdAuthors). `Articles Fractionalized`: 考虑共同写作比例的分数化文章计数。它避免了多作者论文的重复计算。

### H-Index of Authors

[Authors’ Local Impact](Authors'%20Local%20Impact%20-%20Dominance%20ranking%20Authors)

| Element     | h\_index | g\_index |  m\_index |   TC |  NP | PY\_start |
|:------------|---------:|---------:|----------:|-----:|----:|----------:|
| TEO T       |       21 |       28 | 1.2352941 | 2030 |  28 |      2008 |
| TONDEUR J   |       17 |       17 | 1.0000000 | 2483 |  17 |      2008 |
| SELWYN N    |       14 |       20 | 0.5384615 | 1483 |  20 |      1999 |
| HWANG GJ    |       12 |       25 | 0.5714286 | 1093 |  25 |      2004 |
| TSAI CC     |       12 |       16 | 0.9230769 |  727 |  16 |      2012 |
| SPECTOR JM  |        8 |       10 | 0.3809524 |  558 |  10 |      2004 |
| HENDERSON M |        7 |       10 | 0.5833333 |  452 |  10 |      2013 |
| GU XQ       |        5 |       10 | 0.4166667 |  122 |  10 |      2013 |
| CORRIN L    |        3 |        4 | 0.2307692 |   22 |   9 |      2012 |
| LODGE JM    |        3 |        4 | 0.3333333 |   20 |  10 |      2016 |

(*Table above: Dominance ranking Authors*)

Authors’ Local Impact
结果显示每个作者的姓名、h指数、g指数、m指数、总被引量、论文数量、发表起始年份。

-   h指数:反映影响力和论文质量.
-   g指数:考虑论文引用次数分布.
-   m指数:考虑作者生产力.

## Papers 📰

![plot\_spectroscopy](file:/Users/yamlam/Documents/obsdiannote/🧪%20Script%20Labs/Thematic/Educational%20technology/Report_Educational%20technology_files/figure-markdown_strict/reference_Pyramids_base-1.png)

### Reference Pyramids

In the Reference Pyramids method, “Classic Literature” usually refers to the earliest literature that proposes theories or frameworks in a research field, while “core literature” refers to literature that constructively develops or applies those classic works.

When collecting literature on the topic of “Educational technology”, we first identified the top 5 most frequently co-cited papers as the “Classic Literature.” We then counted the number of papers citing each classic paper, and ranked them by citation count. We selected papers with over 77 citations as the “core literature” derived from each classic work. Below, we outline the classic and corresponding core literature in a table format.

The table headers are the Classic Literature. “TI” indicates the paper title, “PY” the publication year, and “TC” the number of citations for each core paper.

![](file:/Users/yamlam/Documents/obsdiannote/🧪%20Script%20Labs/Thematic//Educational%20technology/exports/Pyramids.png)
[html](file:/Users/yamlam/Documents/obsdiannote/🧪%20Script%20Labs/Thematic//Educational%20technology/exports/Pyramids.html)

#### DAVIS FD 1989 MIS QUART

[Note](Pyramid%20-%20DAVIS%20FD%201989%20MIS%20QUART%20.canvas)
\| [DOI](https://sci-hub.ee/10.2307/249008) \| [Link](https://scholar.google.it/scholar?hl=en&as_sdt=0%2C5&q=DAVIS%20FD%201989%20MIS%20QUART)

| TI                                                                                                                                                                                                              |   PY |  TC |
|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----:|----:|
| EFFECTS OF SECURITY AND PRIVACY CONCERNS ON EDUCATIONAL USE OF CLOUD SERVICES                                                                                                                                   | 2015 |  92 |
| MODELING EDUCATIONAL USAGE OF FACEBOOK                                                                                                                                                                          | 2010 | 379 |
| TEACHER ADOPTION OF TECHNOLOGY                                                                                                                                                                                  | 2013 | 118 |
| FACTORS AFFECTING TECHNOLOGY INTEGRATION IN K-12 CLASSROOMS: A PATH MODEL                                                                                                                                       | 2010 | 322 |
| TOWARD AN UNDERSTANDING OF THE BEHAVIORAL INTENTION TO USE A SOCIAL NETWORKING SITE: AN EXTENSION OF TASK-TECHNOLOGY FIT TO SOCIAL-TECHNOLOGY FIT                                                               | 2014 | 112 |
| PERCEIVED PLAYFULNESS, GENDER DIFFERENCES AND TECHNOLOGY ACCEPTANCE MODEL IN A BLENDED LEARNING SCENARIO                                                                                                        | 2013 | 239 |
| EMERGENCY REMOTE TEACHING IN HIGHER EDUCATION: MAPPING THE FIRST GLOBAL ONLINE SEMESTER                                                                                                                         | 2021 | 116 |
| AN ANALYSIS OF THE TECHNOLOGY ACCEPTANCE MODEL IN UNDERSTANDING UNIVERSITY STUDENTS’ BEHAVIORAL INTENTION TO USE E-LEARNING                                                                                     | 2009 | 755 |
| THE TECHNOLOGY ACCEPTANCE MODEL (TAM): A META-ANALYTIC STRUCTURAL EQUATION MODELING APPROACH TO EXPLAINING TEACHERS’ ADOPTION OF DIGITAL TECHNOLOGY IN EDUCATION                                                | 2019 | 578 |
| EXPLORING TEACHER ACCEPTANCE OF E-LEARNING TECHNOLOGY                                                                                                                                                           | 2008 | 173 |
| PRODUCERS’ PERCEPTIONS AND ATTITUDES TOWARD PRECISION AGRICULTURE TECHNOLOGIES                                                                                                                                  | 2005 | 180 |
| ADAPTING THE TECHNOLOGY ACCEPTANCE MODEL TO EVALUATE THE INNOVATIVE POTENTIAL OF E-LEARNING SYSTEMS                                                                                                             | 2014 | 128 |
| STUDENTS’ ACCEPTANCE OF TABLET PCS AND IMPLICATIONS FOR EDUCATIONAL INSTITUTIONS                                                                                                                                | 2011 |  89 |
| A CROSS-CULTURAL EXAMINATION OF THE INTENTION TO USE TECHNOLOGY BETWEEN SINGAPOREAN AND MALAYSIAN PRE-SERVICE TEACHERS: AN APPLICATION OF THE TECHNOLOGY ACCEPTANCE MODEL (TAM)                                 | 2008 | 136 |
| FACTORS AFFECTING TECHNOLOGY USES IN SCHOOLS: AN ECOLOGICAL PERSPECTIVE                                                                                                                                         | 2003 | 254 |
| EXPLICATING THE INFLUENCES THAT EXPLAIN INTENTION TO USE TECHNOLOGY AMONG ENGLISH TEACHERS IN CHINA                                                                                                             | 2018 | 106 |
| FACTORS INFLUENCING PRESERVICE TEACHERS’ INTENTION TO USE TECHNOLOGY: TPACK, TEACHER SELF-EFFICACY, AND TECHNOLOGY ACCEPTANCE MODEL                                                                             | 2018 | 189 |
| EXAMINING THE INFLUENCE OF SUBJECTIVE NORM AND FACILITATING CONDITIONS ON THE INTENTION TO USE TECHNOLOGY AMONG PRE-SERVICE TEACHERS: A STRUCTURAL EQUATION MODELING OF AN EXTENDED TECHNOLOGY ACCEPTANCE MODEL | 2010 | 113 |
| WHERE IS THE “THEORY” WITHIN THE FIELD OF EDUCATIONAL TECHNOLOGY RESEARCH?                                                                                                                                      | 2019 |  91 |
| TECHNOLOGY ACCEPTANCE MODEL IN EDUCATIONAL CONTEXT: A SYSTEMATIC LITERATURE REVIEW                                                                                                                              | 2019 | 269 |
| EXAMINING USER ACCEPTANCE OF COMPUTER TECHNOLOGY: AN EMPIRICAL STUDY OF STUDENT TEACHERS                                                                                                                        | 2005 | 168 |
| PERSONALITY AND TECHNOLOGY ACCEPTANCE: THE INFLUENCE OF PERSONALITY FACTORS ON THE CORE CONSTRUCTS OF THE TECHNOLOGY ACCEPTANCE MODEL                                                                           | 2013 | 201 |
| UNDERSTANDING TECHNOLOGY ADOPTION: THEORY AND FUTURE DIRECTIONS FOR INFORMAL LEARNING                                                                                                                           | 2009 | 526 |
| CLOUD COMPUTING ADOPTION AND USAGE IN COMMUNITY COLLEGES                                                                                                                                                        | 2011 | 146 |
| INVESTIGATING THE ACCEPTANCE OF MOBILE LIBRARY APPLICATIONS WITH AN EXTENDED TECHNOLOGY ACCEPTANCE MODEL (TAM)                                                                                                  | 2020 | 146 |
| CONCEPTUALIZING A MODEL FOR ADOPTION OF CLOUD COMPUTING IN EDUCATION                                                                                                                                            | 2016 | 154 |
| UNDERSTANDING PRE-SERVICE TEACHERS’ COMPUTER ATTITUDES: APPLYING AND EXTENDING THE TECHNOLOGY ACCEPTANCE MODEL                                                                                                  | 2008 | 320 |
| A CROSS-CULTURAL EXAMINATION OF THE IMPACT OF SOCIAL, ORGANISATIONAL AND INDIVIDUAL FACTORS ON EDUCATIONAL TECHNOLOGY ACCEPTANCE BETWEEN BRITISH AND LEBANESE UNIVERSITY STUDENTS                               | 2015 | 116 |
| EVALUATING MULTIPLE ASPECTS OF A DIGITAL EDUCATIONAL PROBLEM-SOLVING-BASED ADVENTURE GAME                                                                                                                       | 2014 |  85 |
| INFORMAL TOOLS IN FORMAL CONTEXTS: DEVELOPMENT OF A MODEL TO ASSESS THE ACCEPTANCE OF MOBILE TECHNOLOGIES AMONG TEACHERS                                                                                        | 2016 | 108 |
| EXPLAINING THE INTENTION TO USE TECHNOLOGY AMONG UNIVERSITY STUDENTS: A STRUCTURAL EQUATION MODELING APPROACH                                                                                                   | 2014 | 134 |
| PREDICTING THE ACCEPTANCE OF MOOCS IN A DEVELOPING COUNTRY: APPLICATION OF TASK-TECHNOLOGY FIT MODEL, SOCIAL MOTIVATION, AND SELF-DETERMINATION THEORY                                                          | 2018 | 147 |
| TECHNOLOGY ACCEPTANCE MODEL IN M-LEARNING CONTEXT: A SYSTEMATIC REVIEW                                                                                                                                          | 2018 | 252 |
| UNDERSTANDING ACADEMICS’ ADOPTION OF LEARNING TECHNOLOGIES: A SYSTEMATIC REVIEW                                                                                                                                 | 2020 |  92 |
| STUDENT ACCEPTANCE OF VIRTUAL LABORATORY AND PRACTICAL WORK: AN EXTENSION OF THE TECHNOLOGY ACCEPTANCE MODEL                                                                                                    | 2019 | 135 |
| ASSESSING THE INTENTION TO USE TECHNOLOGY AMONG PRE-SERVICE TEACHERS IN SINGAPORE AND MALAYSIA: A MULTIGROUP INVARIANCE ANALYSIS OF THE TECHNOLOGY ACCEPTANCE MODEL (TAM)                                       | 2009 | 232 |
| CULTURAL VALUES AND TECHNOLOGY ADOPTION: A MODEL COMPARISON WITH UNIVERSITY TEACHERS FROM CHINA AND SPAIN                                                                                                       | 2019 |  83 |
| FEAR FROM COVID-19 AND TECHNOLOGY ADOPTION: THE IMPACT OF GOOGLE MEET DURING CORONAVIRUS PANDEMIC                                                                                                               | 2023 | 100 |
| CHOOSING BETWEEN THE THEORY OF PLANNED BEHAVIOR (TPB) AND THE TECHNOLOGY ACCEPTANCE MODEL (TAM)                                                                                                                 | 2019 |  88 |
| ONLINE LEARNING USAGE WITHIN YEMENI HIGHER EDUCATION: THE ROLE OF COMPATIBILITY AND TASK-TECHNOLOGY FIT AS MEDIATING VARIABLES IN THE IS SUCCESS MODEL                                                          | 2019 | 118 |

#### VENKATESH V 2003 MIS QUART

[Note](Pyramid%20-%20VENKATESH%20V%202003%20MIS%20QUART%20.canvas)
\| [DOI](https://sci-hub.ee/10.2307/30036540) \| [Link](https://scholar.google.it/scholar?hl=en&as_sdt=0%2C5&q=VENKATESH%20V%202003%20MIS%20QUART)

| TI                                                                                                                                                                                |   PY |  TC |
|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----:|----:|
| EFFECTS OF SECURITY AND PRIVACY CONCERNS ON EDUCATIONAL USE OF CLOUD SERVICES                                                                                                     | 2015 |  92 |
| MODELING EDUCATIONAL USAGE OF FACEBOOK                                                                                                                                            | 2010 | 379 |
| TOWARD AN UNDERSTANDING OF THE BEHAVIORAL INTENTION TO USE A SOCIAL NETWORKING SITE: AN EXTENSION OF TASK-TECHNOLOGY FIT TO SOCIAL-TECHNOLOGY FIT                                 | 2014 | 112 |
| PERCEIVED PLAYFULNESS, GENDER DIFFERENCES AND TECHNOLOGY ACCEPTANCE MODEL IN A BLENDED LEARNING SCENARIO                                                                          | 2013 | 239 |
| THE TECHNOLOGY ACCEPTANCE MODEL (TAM): A META-ANALYTIC STRUCTURAL EQUATION MODELING APPROACH TO EXPLAINING TEACHERS’ ADOPTION OF DIGITAL TECHNOLOGY IN EDUCATION                  | 2019 | 578 |
| EXPLORING TEACHER ACCEPTANCE OF E-LEARNING TECHNOLOGY                                                                                                                             | 2008 | 173 |
| ADAPTING THE TECHNOLOGY ACCEPTANCE MODEL TO EVALUATE THE INNOVATIVE POTENTIAL OF E-LEARNING SYSTEMS                                                                               | 2014 | 128 |
| STUDENTS’ ACCEPTANCE OF TABLET PCS AND IMPLICATIONS FOR EDUCATIONAL INSTITUTIONS                                                                                                  | 2011 |  89 |
| A CROSS-CULTURAL EXAMINATION OF THE INTENTION TO USE TECHNOLOGY BETWEEN SINGAPOREAN AND MALAYSIAN PRE-SERVICE TEACHERS: AN APPLICATION OF THE TECHNOLOGY ACCEPTANCE MODEL (TAM)   | 2008 | 136 |
| WHERE IS THE “THEORY” WITHIN THE FIELD OF EDUCATIONAL TECHNOLOGY RESEARCH?                                                                                                        | 2019 |  91 |
| TECHNOLOGY ACCEPTANCE MODEL IN EDUCATIONAL CONTEXT: A SYSTEMATIC LITERATURE REVIEW                                                                                                | 2019 | 269 |
| PERSONALITY AND TECHNOLOGY ACCEPTANCE: THE INFLUENCE OF PERSONALITY FACTORS ON THE CORE CONSTRUCTS OF THE TECHNOLOGY ACCEPTANCE MODEL                                             | 2013 | 201 |
| UNDERSTANDING TECHNOLOGY ADOPTION: THEORY AND FUTURE DIRECTIONS FOR INFORMAL LEARNING                                                                                             | 2009 | 526 |
| CLOUD COMPUTING ADOPTION AND USAGE IN COMMUNITY COLLEGES                                                                                                                          | 2011 | 146 |
| INVESTIGATING THE ACCEPTANCE OF MOBILE LIBRARY APPLICATIONS WITH AN EXTENDED TECHNOLOGY ACCEPTANCE MODEL (TAM)                                                                    | 2020 | 146 |
| CONCEPTUALIZING A MODEL FOR ADOPTION OF CLOUD COMPUTING IN EDUCATION                                                                                                              | 2016 | 154 |
| UNDERSTANDING PRE-SERVICE TEACHERS’ COMPUTER ATTITUDES: APPLYING AND EXTENDING THE TECHNOLOGY ACCEPTANCE MODEL                                                                    | 2008 | 320 |
| A CROSS-CULTURAL EXAMINATION OF THE IMPACT OF SOCIAL, ORGANISATIONAL AND INDIVIDUAL FACTORS ON EDUCATIONAL TECHNOLOGY ACCEPTANCE BETWEEN BRITISH AND LEBANESE UNIVERSITY STUDENTS | 2015 | 116 |
| INFORMAL TOOLS IN FORMAL CONTEXTS: DEVELOPMENT OF A MODEL TO ASSESS THE ACCEPTANCE OF MOBILE TECHNOLOGIES AMONG TEACHERS                                                          | 2016 | 108 |
| EXPLAINING THE INTENTION TO USE TECHNOLOGY AMONG UNIVERSITY STUDENTS: A STRUCTURAL EQUATION MODELING APPROACH                                                                     | 2014 | 134 |
| PREDICTING THE ACCEPTANCE OF MOOCS IN A DEVELOPING COUNTRY: APPLICATION OF TASK-TECHNOLOGY FIT MODEL, SOCIAL MOTIVATION, AND SELF-DETERMINATION THEORY                            | 2018 | 147 |
| TECHNOLOGY ACCEPTANCE MODEL IN M-LEARNING CONTEXT: A SYSTEMATIC REVIEW                                                                                                            | 2018 | 252 |
| STUDENT ACCEPTANCE OF VIRTUAL LABORATORY AND PRACTICAL WORK: AN EXTENSION OF THE TECHNOLOGY ACCEPTANCE MODEL                                                                      | 2019 | 135 |
| ASSESSING THE INTENTION TO USE TECHNOLOGY AMONG PRE-SERVICE TEACHERS IN SINGAPORE AND MALAYSIA: A MULTIGROUP INVARIANCE ANALYSIS OF THE TECHNOLOGY ACCEPTANCE MODEL (TAM)         | 2009 | 232 |
| CULTURAL VALUES AND TECHNOLOGY ADOPTION: A MODEL COMPARISON WITH UNIVERSITY TEACHERS FROM CHINA AND SPAIN                                                                         | 2019 |  83 |
| FEAR FROM COVID-19 AND TECHNOLOGY ADOPTION: THE IMPACT OF GOOGLE MEET DURING CORONAVIRUS PANDEMIC                                                                                 | 2023 | 100 |
| CHOOSING BETWEEN THE THEORY OF PLANNED BEHAVIOR (TPB) AND THE TECHNOLOGY ACCEPTANCE MODEL (TAM)                                                                                   | 2019 |  88 |
| EDUCATIONAL MAGIC TOYS DEVELOPED WITH AUGMENTED REALITY TECHNOLOGY FOR EARLY CHILDHOOD EDUCATION                                                                                  | 2016 | 143 |
| A PATH ANALYSIS OF PRE-SERVICE TEACHERS’ ATTITUDES TO COMPUTER USE: APPLYING AND EXTENDING THE TECHNOLOGY ACCEPTANCE MODEL IN AN EDUCATIONAL CONTEXT                              | 2010 | 150 |
| UNPACKING TEACHERS’ INTENTIONS TO INTEGRATE TECHNOLOGY: A META-ANALYSIS                                                                                                           | 2019 |  80 |
| THE IMPORTANCE OF ATTITUDES TOWARD TECHNOLOGY FOR PRE-SERVICE TEACHERS’ TECHNOLOGICAL, PEDAGOGICAL, AND CONTENT KNOWLEDGE: COMPARING STRUCTURAL EQUATION MODELING APPROACHES      | 2018 |  99 |

#### MISHRA P 2006 TEACH COLL REC

[Note](Pyramid%20-%20MISHRA%20P%202006%20TEACH%20COLL%20REC%20.canvas)
\| [DOI](https://sci-hub.ee/10.1111/J.1467-9620.2006.00684.X) \| [Link](https://scholar.google.it/scholar?hl=en&as_sdt=0%2C5&q=MISHRA%20P%202006%20TEACH%20COLL%20REC)

| TI                                                                                                                                                                           |   PY |  TC |
|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----:|----:|
| THE TECHNOLOGY ACCEPTANCE MODEL (TAM): A META-ANALYTIC STRUCTURAL EQUATION MODELING APPROACH TO EXPLAINING TEACHERS’ ADOPTION OF DIGITAL TECHNOLOGY IN EDUCATION             | 2019 | 578 |
| FACTORS INFLUENCING PRESERVICE TEACHERS’ INTENTION TO USE TECHNOLOGY: TPACK, TEACHER SELF-EFFICACY, AND TECHNOLOGY ACCEPTANCE MODEL                                          | 2018 | 189 |
| WHERE IS THE “THEORY” WITHIN THE FIELD OF EDUCATIONAL TECHNOLOGY RESEARCH?                                                                                                   | 2019 |  91 |
| THE IMPORTANCE OF ATTITUDES TOWARD TECHNOLOGY FOR PRE-SERVICE TEACHERS’ TECHNOLOGICAL, PEDAGOGICAL, AND CONTENT KNOWLEDGE: COMPARING STRUCTURAL EQUATION MODELING APPROACHES | 2018 |  99 |
| SELF-PERCEPTION OF THE DIGITAL COMPETENCE OF EDUCATORS DURING THE COVID-19 PANDEMIC: A CROSS-ANALYSIS OF DIFFERENT EDUCATIONAL STAGES                                        | 2020 |  95 |
| PROFESSIONAL DEVELOPMENT FOR TECHNOLOGY-ENHANCED INQUIRY SCIENCE                                                                                                             | 2011 |  87 |
| UNDERSTANDING PRESERVICE TEACHERS’ TECHNOLOGY USE THROUGH TPACK FRAMEWORK                                                                                                    | 2012 |  87 |
| INFUSING CREATIVITY AND TECHNOLOGY IN 21ST CENTURY EDUCATION: A SYSTEMIC VIEW FOR CHANGE                                                                                     | 2016 |  98 |
| EDUCATIONAL TECHNOLOGIES IN PROBLEM-BASED LEARNING IN HEALTH SCIENCES EDUCATION: A SYSTEMATIC REVIEW                                                                         | 2014 |  88 |
| WHAT ARE THE EDUCATIONAL AFFORDANCES OF WEARABLE TECHNOLOGIES?                                                                                                               | 2015 | 124 |
| INVESTIGATING TPACK: KNOWLEDGE GROWTH IN TEACHING WITH TECHNOLOGY                                                                                                            | 2011 | 124 |
| TEACHER BELIEFS AND TECHNOLOGY INTEGRATION                                                                                                                                   | 2013 | 326 |
| TEACHER EDUCATORS’ COMPETENCES IN FOSTERING STUDENT TEACHERS’ PROFICIENCY IN TEACHING AND LEARNING WITH TECHNOLOGY: AN OVERVIEW OF RELEVANT RESEARCH LITERATURE              | 2018 | 105 |
| EVIDENCE OF IMPACT: TRANSFORMING TEACHER EDUCATION WITH PREPARING TOMORROW’S TEACHERS TO TEACH WITH TECHNOLOGY (PT3) GRANTS                                                  | 2010 | 175 |
| TECHNOLOGY-MEDIATED LEARNING THEORY                                                                                                                                          | 2019 |  91 |

#### VENKATESH V 2000 MANAGE SCI

[Note](Pyramid%20-%20VENKATESH%20V%202000%20MANAGE%20SCI%20.canvas)
\| [DOI](https://sci-hub.ee/10.1287/MNSC.46.2.186.11926) \| [Link](https://scholar.google.it/scholar?hl=en&as_sdt=0%2C5&q=VENKATESH%20V%202000%20MANAGE%20SCI)

| TI                                                                                                                                                                                                              |   PY |  TC |
|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----:|----:|
| MODELING EDUCATIONAL USAGE OF FACEBOOK                                                                                                                                                                          | 2010 | 379 |
| PERCEIVED PLAYFULNESS, GENDER DIFFERENCES AND TECHNOLOGY ACCEPTANCE MODEL IN A BLENDED LEARNING SCENARIO                                                                                                        | 2013 | 239 |
| AN ANALYSIS OF THE TECHNOLOGY ACCEPTANCE MODEL IN UNDERSTANDING UNIVERSITY STUDENTS’ BEHAVIORAL INTENTION TO USE E-LEARNING                                                                                     | 2009 | 755 |
| EXPLORING TEACHER ACCEPTANCE OF E-LEARNING TECHNOLOGY                                                                                                                                                           | 2008 | 173 |
| PRODUCERS’ PERCEPTIONS AND ATTITUDES TOWARD PRECISION AGRICULTURE TECHNOLOGIES                                                                                                                                  | 2005 | 180 |
| ADAPTING THE TECHNOLOGY ACCEPTANCE MODEL TO EVALUATE THE INNOVATIVE POTENTIAL OF E-LEARNING SYSTEMS                                                                                                             | 2014 | 128 |
| STUDENTS’ ACCEPTANCE OF TABLET PCS AND IMPLICATIONS FOR EDUCATIONAL INSTITUTIONS                                                                                                                                | 2011 |  89 |
| EXPLICATING THE INFLUENCES THAT EXPLAIN INTENTION TO USE TECHNOLOGY AMONG ENGLISH TEACHERS IN CHINA                                                                                                             | 2018 | 106 |
| FACTORS INFLUENCING PRESERVICE TEACHERS’ INTENTION TO USE TECHNOLOGY: TPACK, TEACHER SELF-EFFICACY, AND TECHNOLOGY ACCEPTANCE MODEL                                                                             | 2018 | 189 |
| EXAMINING THE INFLUENCE OF SUBJECTIVE NORM AND FACILITATING CONDITIONS ON THE INTENTION TO USE TECHNOLOGY AMONG PRE-SERVICE TEACHERS: A STRUCTURAL EQUATION MODELING OF AN EXTENDED TECHNOLOGY ACCEPTANCE MODEL | 2010 | 113 |
| WHERE IS THE “THEORY” WITHIN THE FIELD OF EDUCATIONAL TECHNOLOGY RESEARCH?                                                                                                                                      | 2019 |  91 |
| EXAMINING USER ACCEPTANCE OF COMPUTER TECHNOLOGY: AN EMPIRICAL STUDY OF STUDENT TEACHERS                                                                                                                        | 2005 | 168 |
| CLOUD COMPUTING ADOPTION AND USAGE IN COMMUNITY COLLEGES                                                                                                                                                        | 2011 | 146 |
| UNDERSTANDING PRE-SERVICE TEACHERS’ COMPUTER ATTITUDES: APPLYING AND EXTENDING THE TECHNOLOGY ACCEPTANCE MODEL                                                                                                  | 2008 | 320 |
| A CROSS-CULTURAL EXAMINATION OF THE IMPACT OF SOCIAL, ORGANISATIONAL AND INDIVIDUAL FACTORS ON EDUCATIONAL TECHNOLOGY ACCEPTANCE BETWEEN BRITISH AND LEBANESE UNIVERSITY STUDENTS                               | 2015 | 116 |
| INFORMAL TOOLS IN FORMAL CONTEXTS: DEVELOPMENT OF A MODEL TO ASSESS THE ACCEPTANCE OF MOBILE TECHNOLOGIES AMONG TEACHERS                                                                                        | 2016 | 108 |
| EXPLAINING THE INTENTION TO USE TECHNOLOGY AMONG UNIVERSITY STUDENTS: A STRUCTURAL EQUATION MODELING APPROACH                                                                                                   | 2014 | 134 |
| STUDENT ACCEPTANCE OF VIRTUAL LABORATORY AND PRACTICAL WORK: AN EXTENSION OF THE TECHNOLOGY ACCEPTANCE MODEL                                                                                                    | 2019 | 135 |
| ASSESSING THE INTENTION TO USE TECHNOLOGY AMONG PRE-SERVICE TEACHERS IN SINGAPORE AND MALAYSIA: A MULTIGROUP INVARIANCE ANALYSIS OF THE TECHNOLOGY ACCEPTANCE MODEL (TAM)                                       | 2009 | 232 |
| CULTURAL VALUES AND TECHNOLOGY ADOPTION: A MODEL COMPARISON WITH UNIVERSITY TEACHERS FROM CHINA AND SPAIN                                                                                                       | 2019 |  83 |
| FEAR FROM COVID-19 AND TECHNOLOGY ADOPTION: THE IMPACT OF GOOGLE MEET DURING CORONAVIRUS PANDEMIC                                                                                                               | 2023 | 100 |
| CHOOSING BETWEEN THE THEORY OF PLANNED BEHAVIOR (TPB) AND THE TECHNOLOGY ACCEPTANCE MODEL (TAM)                                                                                                                 | 2019 |  88 |
| A PATH ANALYSIS OF PRE-SERVICE TEACHERS’ ATTITUDES TO COMPUTER USE: APPLYING AND EXTENDING THE TECHNOLOGY ACCEPTANCE MODEL IN AN EDUCATIONAL CONTEXT                                                            | 2010 | 150 |
| TEACHERS’ ONLINE TEACHING EXPECTATIONS AND EXPERIENCES DURING THE COVID19-PANDEMIC IN THE NETHERLANDS                                                                                                           | 2020 | 106 |

#### FORNELL C 1981 J MARKETING RES

[Note](Pyramid%20-%20FORNELL%20C%201981%20J%20MARKETING%20RES%20.canvas)
\| [DOI](https://sci-hub.ee/10.2307/3151312) \| [Link](https://scholar.google.it/scholar?hl=en&as_sdt=0%2C5&q=FORNELL%20C%201981%20J%20MARKETING%20RES)

| TI                                                                                                                                                                                                              |   PY |  TC |
|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----:|----:|
| PRODUCERS’ PERCEPTIONS AND ATTITUDES TOWARD PRECISION AGRICULTURE TECHNOLOGIES                                                                                                                                  | 2005 | 180 |
| STUDENTS’ ACCEPTANCE OF TABLET PCS AND IMPLICATIONS FOR EDUCATIONAL INSTITUTIONS                                                                                                                                | 2011 |  89 |
| A CROSS-CULTURAL EXAMINATION OF THE INTENTION TO USE TECHNOLOGY BETWEEN SINGAPOREAN AND MALAYSIAN PRE-SERVICE TEACHERS: AN APPLICATION OF THE TECHNOLOGY ACCEPTANCE MODEL (TAM)                                 | 2008 | 136 |
| EXPLICATING THE INFLUENCES THAT EXPLAIN INTENTION TO USE TECHNOLOGY AMONG ENGLISH TEACHERS IN CHINA                                                                                                             | 2018 | 106 |
| EXAMINING THE INFLUENCE OF SUBJECTIVE NORM AND FACILITATING CONDITIONS ON THE INTENTION TO USE TECHNOLOGY AMONG PRE-SERVICE TEACHERS: A STRUCTURAL EQUATION MODELING OF AN EXTENDED TECHNOLOGY ACCEPTANCE MODEL | 2010 | 113 |
| INVESTIGATING THE ACCEPTANCE OF MOBILE LIBRARY APPLICATIONS WITH AN EXTENDED TECHNOLOGY ACCEPTANCE MODEL (TAM)                                                                                                  | 2020 | 146 |
| CONCEPTUALIZING A MODEL FOR ADOPTION OF CLOUD COMPUTING IN EDUCATION                                                                                                                                            | 2016 | 154 |
| UNDERSTANDING PRE-SERVICE TEACHERS’ COMPUTER ATTITUDES: APPLYING AND EXTENDING THE TECHNOLOGY ACCEPTANCE MODEL                                                                                                  | 2008 | 320 |
| EXPLAINING THE INTENTION TO USE TECHNOLOGY AMONG UNIVERSITY STUDENTS: A STRUCTURAL EQUATION MODELING APPROACH                                                                                                   | 2014 | 134 |
| STUDENT ACCEPTANCE OF VIRTUAL LABORATORY AND PRACTICAL WORK: AN EXTENSION OF THE TECHNOLOGY ACCEPTANCE MODEL                                                                                                    | 2019 | 135 |
| ASSESSING THE INTENTION TO USE TECHNOLOGY AMONG PRE-SERVICE TEACHERS IN SINGAPORE AND MALAYSIA: A MULTIGROUP INVARIANCE ANALYSIS OF THE TECHNOLOGY ACCEPTANCE MODEL (TAM)                                       | 2009 | 232 |
| FEAR FROM COVID-19 AND TECHNOLOGY ADOPTION: THE IMPACT OF GOOGLE MEET DURING CORONAVIRUS PANDEMIC                                                                                                               | 2023 | 100 |
| ONLINE LEARNING USAGE WITHIN YEMENI HIGHER EDUCATION: THE ROLE OF COMPATIBILITY AND TASK-TECHNOLOGY FIT AS MEDIATING VARIABLES IN THE IS SUCCESS MODEL                                                          | 2019 | 118 |
| A PATH ANALYSIS OF PRE-SERVICE TEACHERS’ ATTITUDES TO COMPUTER USE: APPLYING AND EXTENDING THE TECHNOLOGY ACCEPTANCE MODEL IN AN EDUCATIONAL CONTEXT                                                            | 2010 | 150 |
| USE OF E-LEARNING BY UNIVERSITY STUDENTS IN MALAYSIAN HIGHER EDUCATIONAL INSTITUTIONS: A CASE IN UNIVERSITI TEKNOLOGI MALAYSIA                                                                                  | 2018 |  78 |

Taks:

-   Outline the theories or frameworks proposed in each classic work, and describe how the core papers develop and apply them.

-   Evaluate the role of each Classic Literature group and associated core papers in “Educational technology”.

-   Identify differences in discussion topics between them.

-   Use the MoSCoW method to develop a reading plan for each Classic Literature group.

### Most Cited Papers

| Paper                               | DOI                           | TC   | TCperYear | NTC   |
|:------------------------------------|:------------------------------|:-----|:----------|:------|
| DESANCTIS G, 1994, ORGAN SCI        | 10.1287/orsc.5.2.121          | 1703 | 54.94     | 19.89 |
| AIKEN LH, 2003, JAMA-J AM MED ASSOC | 10.1001/jama.290.12.1617      | 1065 | 48.41     | 16.96 |
| HEW KF, 2007, ETR&D-EDUC TECH RES   | 10.1007/s11423-006-9022-5     | 853  | 47.39     | 17.12 |
| AKÇAYIR M, 2017, EDUC RES REV-NETH  | 10.1016/j.edurev.2016.11.002  | 808  | 101.00    | 27.89 |
| ERTMER PA, 2012, COMPUT EDUC        | 10.1016/j.compedu.2012.02.001 | 759  | 58.38     | 18.74 |

(*Table above: Top manuscripts per citations*)

Source summary: [csv](file:/Users/yamlam/Documents/obsdiannote/🧪%20Script%20Labs/Thematic//Educational%20technology/exports/S0-BasicStatistics-MostCitedPapers-Educational%20technology.csv).
Relavant note: [TCperYear\_and\_NTC\_oF\_Paper](TCperYear%20and%20NTC%20of%20Paper).

## Sources 🏫

### Most Relevant Sources

| Sources                                               | Articles |
|:------------------------------------------------------|:---------|
| BRITISH JOURNAL OF EDUCATIONAL TECHNOLOGY             | 216      |
| ETR&D-EDUCATIONAL TECHNOLOGY RESEARCH AND DEVELOPMENT | 207      |
| EDUCATIONAL TECHNOLOGY & SOCIETY                      | 170      |
| EDUCATION AND INFORMATION TECHNOLOGIES                | 145      |
| SUSTAINABILITY                                        | 138      |

(*Table above: Most Relevant Keywords*)

| Author Keywords (DE)   | Articles | Keywords-Plus (ID) | Articles |
|:-----------------------|:---------|:-------------------|:---------|
| EDUCATIONAL TECHNOLOGY | 550      | STUDENTS           | 306      |
| TECHNOLOGY             | 376      | EDUCATION          | 265      |
| EDUCATION              | 168      | KNOWLEDGE          | 231      |
| HIGHER EDUCATION       | 168      | TECHNOLOGY         | 196      |
| TECHNOLOGY INTEGRATION | 156      | IMPACT             | 189      |

(*Table above: Most Relevant Keywords*)

## MATADATE

Searching:: Educational technology
Timespan:: 1957:2023
Sources (Journals, Books, etc):: 901
Documents:: 4390
Annual Growth Rate %:: 9.64
Document Average Age:: 12.3
Average citations per doc:: 21.32
Average citations per year per doc:: 2.4
References:: 148383
article:: 3600
article; book chapter:: 1
article; early access:: 118
article; proceedings paper:: 78
article; retracted publication:: 2
book review:: 135
book review; early access:: 1
correction:: 1
correction, addition:: 1
discussion:: 2
editorial material:: 112
letter:: 5
meeting abstract:: 17
note:: 6
reprint:: 1
review:: 291
review; early access:: 19
Keywords Plus (ID):: 3596
Author’s Keywords (DE):: 8336
Authors:: 10012
Author Appearances:: 12216
Authors of single-authored docs:: 1105
Single-authored docs:: 1263
Documents per Author:: 0.438
Co-Authors per Doc:: 2.78
International co-authorships %:: 16.47
